[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/stock/*"
  to = "/.netlify/functions/stock/stock/:splat"
  status = 200

[[redirects]]
  from = "/fgi"
  to = "/.netlify/functions/stock/fgi"
  status = 200

[[redirects]]
  from = "/news/*"
  to = "/.netlify/functions/stock/news/:splat"
  status = 200
